// Code Generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package amm_v3

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// InitializeReward is the `initializeReward` instruction.
type InitializeReward struct {
	Param *InitializeRewardParam

	// [0] = [WRITE, SIGNER] rewardFunder
	//
	// [1] = [WRITE] funderTokenAccount
	//
	// [2] = [] ammConfig
	//
	// [3] = [WRITE] poolState
	//
	// [4] = [] operationState
	//
	// [5] = [] rewardTokenMint
	//
	// [6] = [WRITE] rewardTokenVault
	//
	// [7] = [] tokenProgram
	//
	// [8] = [] systemProgram
	//
	// [9] = [] rent
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewInitializeRewardInstructionBuilder creates a new `InitializeReward` instruction builder.
func NewInitializeRewardInstructionBuilder() *InitializeReward {
	nd := &InitializeReward{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 10),
	}
	return nd
}

// SetParam sets the "param" parameter.
func (inst *InitializeReward) SetParam(param InitializeRewardParam) *InitializeReward {
	inst.Param = &param
	return inst
}

// SetRewardFunderAccount sets the "rewardFunder" account.
func (inst *InitializeReward) SetRewardFunderAccount(rewardFunder ag_solanago.PublicKey) *InitializeReward {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(rewardFunder).WRITE().SIGNER()
	return inst
}

// GetRewardFunderAccount gets the "rewardFunder" account.
func (inst *InitializeReward) GetRewardFunderAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetFunderTokenAccountAccount sets the "funderTokenAccount" account.
func (inst *InitializeReward) SetFunderTokenAccountAccount(funderTokenAccount ag_solanago.PublicKey) *InitializeReward {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(funderTokenAccount).WRITE()
	return inst
}

// GetFunderTokenAccountAccount gets the "funderTokenAccount" account.
func (inst *InitializeReward) GetFunderTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetAmmConfigAccount sets the "ammConfig" account.
func (inst *InitializeReward) SetAmmConfigAccount(ammConfig ag_solanago.PublicKey) *InitializeReward {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(ammConfig)
	return inst
}

// GetAmmConfigAccount gets the "ammConfig" account.
func (inst *InitializeReward) GetAmmConfigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetPoolStateAccount sets the "poolState" account.
func (inst *InitializeReward) SetPoolStateAccount(poolState ag_solanago.PublicKey) *InitializeReward {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(poolState).WRITE()
	return inst
}

// GetPoolStateAccount gets the "poolState" account.
func (inst *InitializeReward) GetPoolStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetOperationStateAccount sets the "operationState" account.
func (inst *InitializeReward) SetOperationStateAccount(operationState ag_solanago.PublicKey) *InitializeReward {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(operationState)
	return inst
}

// GetOperationStateAccount gets the "operationState" account.
func (inst *InitializeReward) GetOperationStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetRewardTokenMintAccount sets the "rewardTokenMint" account.
func (inst *InitializeReward) SetRewardTokenMintAccount(rewardTokenMint ag_solanago.PublicKey) *InitializeReward {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(rewardTokenMint)
	return inst
}

// GetRewardTokenMintAccount gets the "rewardTokenMint" account.
func (inst *InitializeReward) GetRewardTokenMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetRewardTokenVaultAccount sets the "rewardTokenVault" account.
func (inst *InitializeReward) SetRewardTokenVaultAccount(rewardTokenVault ag_solanago.PublicKey) *InitializeReward {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(rewardTokenVault).WRITE()
	return inst
}

// GetRewardTokenVaultAccount gets the "rewardTokenVault" account.
func (inst *InitializeReward) GetRewardTokenVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *InitializeReward) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *InitializeReward {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *InitializeReward) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *InitializeReward) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *InitializeReward {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *InitializeReward) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetRentAccount sets the "rent" account.
func (inst *InitializeReward) SetRentAccount(rent ag_solanago.PublicKey) *InitializeReward {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(rent)
	return inst
}

// GetRentAccount gets the "rent" account.
func (inst *InitializeReward) GetRentAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

func (inst InitializeReward) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_InitializeReward,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst InitializeReward) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *InitializeReward) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Param == nil {
			return errors.New("Param parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.RewardFunder is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.FunderTokenAccount is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.AmmConfig is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.PoolState is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.OperationState is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.RewardTokenMint is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.RewardTokenVault is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.Rent is not set")
		}
	}
	return nil
}

func (inst *InitializeReward) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("InitializeReward")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Param", *inst.Param))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=10]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("    rewardFunder", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("     funderToken", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("       ammConfig", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("       poolState", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("  operationState", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta(" rewardTokenMint", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("rewardTokenVault", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("    tokenProgram", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("   systemProgram", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("            rent", inst.AccountMetaSlice.Get(9)))
					})
				})
		})
}

func (obj InitializeReward) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Param` param:
	err = encoder.Encode(obj.Param)
	if err != nil {
		return err
	}
	return nil
}
func (obj *InitializeReward) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Param`:
	err = decoder.Decode(&obj.Param)
	if err != nil {
		return err
	}
	return nil
}

// NewInitializeRewardInstruction declares a new InitializeReward instruction with the provided parameters and accounts.
func NewInitializeRewardInstruction(
	// Parameters:
	param InitializeRewardParam,
	// Accounts:
	rewardFunder ag_solanago.PublicKey,
	funderTokenAccount ag_solanago.PublicKey,
	ammConfig ag_solanago.PublicKey,
	poolState ag_solanago.PublicKey,
	operationState ag_solanago.PublicKey,
	rewardTokenMint ag_solanago.PublicKey,
	rewardTokenVault ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	rent ag_solanago.PublicKey) *InitializeReward {
	return NewInitializeRewardInstructionBuilder().
		SetParam(param).
		SetRewardFunderAccount(rewardFunder).
		SetFunderTokenAccountAccount(funderTokenAccount).
		SetAmmConfigAccount(ammConfig).
		SetPoolStateAccount(poolState).
		SetOperationStateAccount(operationState).
		SetRewardTokenMintAccount(rewardTokenMint).
		SetRewardTokenVaultAccount(rewardTokenVault).
		SetTokenProgramAccount(tokenProgram).
		SetSystemProgramAccount(systemProgram).
		SetRentAccount(rent)
}
