// Code Generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package amm_v3

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// ResetSqrtPrice is the `resetSqrtPrice` instruction.
type ResetSqrtPrice struct {
	SqrtPriceX64 *ag_binary.Uint128

	// [0] = [SIGNER] owner
	//
	// [1] = [WRITE] poolState
	//
	// [2] = [WRITE] tokenVault0
	//
	// [3] = [WRITE] tokenVault1
	//
	// [4] = [WRITE] observationState
	//
	// [5] = [WRITE] recipientTokenAccount0
	//
	// [6] = [WRITE] recipientTokenAccount1
	//
	// [7] = [] tokenProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewResetSqrtPriceInstructionBuilder creates a new `ResetSqrtPrice` instruction builder.
func NewResetSqrtPriceInstructionBuilder() *ResetSqrtPrice {
	nd := &ResetSqrtPrice{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 8),
	}
	return nd
}

// SetSqrtPriceX64 sets the "sqrtPriceX64" parameter.
func (inst *ResetSqrtPrice) SetSqrtPriceX64(sqrtPriceX64 ag_binary.Uint128) *ResetSqrtPrice {
	inst.SqrtPriceX64 = &sqrtPriceX64
	return inst
}

// SetOwnerAccount sets the "owner" account.
func (inst *ResetSqrtPrice) SetOwnerAccount(owner ag_solanago.PublicKey) *ResetSqrtPrice {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(owner).SIGNER()
	return inst
}

// GetOwnerAccount gets the "owner" account.
func (inst *ResetSqrtPrice) GetOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetPoolStateAccount sets the "poolState" account.
func (inst *ResetSqrtPrice) SetPoolStateAccount(poolState ag_solanago.PublicKey) *ResetSqrtPrice {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(poolState).WRITE()
	return inst
}

// GetPoolStateAccount gets the "poolState" account.
func (inst *ResetSqrtPrice) GetPoolStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetTokenVault0Account sets the "tokenVault0" account.
func (inst *ResetSqrtPrice) SetTokenVault0Account(tokenVault0 ag_solanago.PublicKey) *ResetSqrtPrice {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(tokenVault0).WRITE()
	return inst
}

// GetTokenVault0Account gets the "tokenVault0" account.
func (inst *ResetSqrtPrice) GetTokenVault0Account() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetTokenVault1Account sets the "tokenVault1" account.
func (inst *ResetSqrtPrice) SetTokenVault1Account(tokenVault1 ag_solanago.PublicKey) *ResetSqrtPrice {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(tokenVault1).WRITE()
	return inst
}

// GetTokenVault1Account gets the "tokenVault1" account.
func (inst *ResetSqrtPrice) GetTokenVault1Account() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetObservationStateAccount sets the "observationState" account.
func (inst *ResetSqrtPrice) SetObservationStateAccount(observationState ag_solanago.PublicKey) *ResetSqrtPrice {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(observationState).WRITE()
	return inst
}

// GetObservationStateAccount gets the "observationState" account.
func (inst *ResetSqrtPrice) GetObservationStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetRecipientTokenAccount0Account sets the "recipientTokenAccount0" account.
func (inst *ResetSqrtPrice) SetRecipientTokenAccount0Account(recipientTokenAccount0 ag_solanago.PublicKey) *ResetSqrtPrice {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(recipientTokenAccount0).WRITE()
	return inst
}

// GetRecipientTokenAccount0Account gets the "recipientTokenAccount0" account.
func (inst *ResetSqrtPrice) GetRecipientTokenAccount0Account() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetRecipientTokenAccount1Account sets the "recipientTokenAccount1" account.
func (inst *ResetSqrtPrice) SetRecipientTokenAccount1Account(recipientTokenAccount1 ag_solanago.PublicKey) *ResetSqrtPrice {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(recipientTokenAccount1).WRITE()
	return inst
}

// GetRecipientTokenAccount1Account gets the "recipientTokenAccount1" account.
func (inst *ResetSqrtPrice) GetRecipientTokenAccount1Account() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *ResetSqrtPrice) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *ResetSqrtPrice {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *ResetSqrtPrice) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

func (inst ResetSqrtPrice) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_ResetSqrtPrice,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst ResetSqrtPrice) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *ResetSqrtPrice) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.SqrtPriceX64 == nil {
			return errors.New("SqrtPriceX64 parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Owner is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.PoolState is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.TokenVault0 is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.TokenVault1 is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.ObservationState is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.RecipientTokenAccount0 is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.RecipientTokenAccount1 is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
	}
	return nil
}

func (inst *ResetSqrtPrice) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("ResetSqrtPrice")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("SqrtPriceX64", *inst.SqrtPriceX64))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=8]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("                 owner", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("             poolState", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("           tokenVault0", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("           tokenVault1", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("      observationState", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("recipientTokenAccount0", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("recipientTokenAccount1", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("          tokenProgram", inst.AccountMetaSlice.Get(7)))
					})
				})
		})
}

func (obj ResetSqrtPrice) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `SqrtPriceX64` param:
	err = encoder.Encode(obj.SqrtPriceX64)
	if err != nil {
		return err
	}
	return nil
}
func (obj *ResetSqrtPrice) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `SqrtPriceX64`:
	err = decoder.Decode(&obj.SqrtPriceX64)
	if err != nil {
		return err
	}
	return nil
}

// NewResetSqrtPriceInstruction declares a new ResetSqrtPrice instruction with the provided parameters and accounts.
func NewResetSqrtPriceInstruction(
	// Parameters:
	sqrtPriceX64 ag_binary.Uint128,
	// Accounts:
	owner ag_solanago.PublicKey,
	poolState ag_solanago.PublicKey,
	tokenVault0 ag_solanago.PublicKey,
	tokenVault1 ag_solanago.PublicKey,
	observationState ag_solanago.PublicKey,
	recipientTokenAccount0 ag_solanago.PublicKey,
	recipientTokenAccount1 ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey) *ResetSqrtPrice {
	return NewResetSqrtPriceInstructionBuilder().
		SetSqrtPriceX64(sqrtPriceX64).
		SetOwnerAccount(owner).
		SetPoolStateAccount(poolState).
		SetTokenVault0Account(tokenVault0).
		SetTokenVault1Account(tokenVault1).
		SetObservationStateAccount(observationState).
		SetRecipientTokenAccount0Account(recipientTokenAccount0).
		SetRecipientTokenAccount1Account(recipientTokenAccount1).
		SetTokenProgramAccount(tokenProgram)
}
