// Code Generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package amm_v3

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Swap is the `swap` instruction.
type Swap struct {
	Amount               *uint64
	OtherAmountThreshold *uint64
	SqrtPriceLimitX64    *ag_binary.Uint128
	IsBaseInput          *bool

	// [0] = [SIGNER] payer
	//
	// [1] = [] ammConfig
	//
	// [2] = [WRITE] poolState
	//
	// [3] = [WRITE] inputTokenAccount
	//
	// [4] = [WRITE] outputTokenAccount
	//
	// [5] = [WRITE] inputVault
	//
	// [6] = [WRITE] outputVault
	//
	// [7] = [WRITE] observationState
	//
	// [8] = [] tokenProgram
	//
	// [9] = [WRITE] tickArray
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewSwapInstructionBuilder creates a new `Swap` instruction builder.
func NewSwapInstructionBuilder() *Swap {
	nd := &Swap{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 10),
	}
	return nd
}

// SetAmount sets the "amount" parameter.
func (inst *Swap) SetAmount(amount uint64) *Swap {
	inst.Amount = &amount
	return inst
}

// SetOtherAmountThreshold sets the "otherAmountThreshold" parameter.
func (inst *Swap) SetOtherAmountThreshold(otherAmountThreshold uint64) *Swap {
	inst.OtherAmountThreshold = &otherAmountThreshold
	return inst
}

// SetSqrtPriceLimitX64 sets the "sqrtPriceLimitX64" parameter.
func (inst *Swap) SetSqrtPriceLimitX64(sqrtPriceLimitX64 ag_binary.Uint128) *Swap {
	inst.SqrtPriceLimitX64 = &sqrtPriceLimitX64
	return inst
}

// SetIsBaseInput sets the "isBaseInput" parameter.
func (inst *Swap) SetIsBaseInput(isBaseInput bool) *Swap {
	inst.IsBaseInput = &isBaseInput
	return inst
}

// SetPayerAccount sets the "payer" account.
func (inst *Swap) SetPayerAccount(payer ag_solanago.PublicKey) *Swap {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(payer).SIGNER()
	return inst
}

// GetPayerAccount gets the "payer" account.
func (inst *Swap) GetPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAmmConfigAccount sets the "ammConfig" account.
func (inst *Swap) SetAmmConfigAccount(ammConfig ag_solanago.PublicKey) *Swap {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(ammConfig)
	return inst
}

// GetAmmConfigAccount gets the "ammConfig" account.
func (inst *Swap) GetAmmConfigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetPoolStateAccount sets the "poolState" account.
func (inst *Swap) SetPoolStateAccount(poolState ag_solanago.PublicKey) *Swap {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(poolState).WRITE()
	return inst
}

// GetPoolStateAccount gets the "poolState" account.
func (inst *Swap) GetPoolStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetInputTokenAccountAccount sets the "inputTokenAccount" account.
func (inst *Swap) SetInputTokenAccountAccount(inputTokenAccount ag_solanago.PublicKey) *Swap {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(inputTokenAccount).WRITE()
	return inst
}

// GetInputTokenAccountAccount gets the "inputTokenAccount" account.
func (inst *Swap) GetInputTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetOutputTokenAccountAccount sets the "outputTokenAccount" account.
func (inst *Swap) SetOutputTokenAccountAccount(outputTokenAccount ag_solanago.PublicKey) *Swap {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(outputTokenAccount).WRITE()
	return inst
}

// GetOutputTokenAccountAccount gets the "outputTokenAccount" account.
func (inst *Swap) GetOutputTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetInputVaultAccount sets the "inputVault" account.
func (inst *Swap) SetInputVaultAccount(inputVault ag_solanago.PublicKey) *Swap {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(inputVault).WRITE()
	return inst
}

// GetInputVaultAccount gets the "inputVault" account.
func (inst *Swap) GetInputVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetOutputVaultAccount sets the "outputVault" account.
func (inst *Swap) SetOutputVaultAccount(outputVault ag_solanago.PublicKey) *Swap {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(outputVault).WRITE()
	return inst
}

// GetOutputVaultAccount gets the "outputVault" account.
func (inst *Swap) GetOutputVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetObservationStateAccount sets the "observationState" account.
func (inst *Swap) SetObservationStateAccount(observationState ag_solanago.PublicKey) *Swap {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(observationState).WRITE()
	return inst
}

// GetObservationStateAccount gets the "observationState" account.
func (inst *Swap) GetObservationStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *Swap) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *Swap {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *Swap) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetTickArrayAccount sets the "tickArray" account.
func (inst *Swap) SetTickArrayAccount(tickArray ag_solanago.PublicKey) *Swap {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(tickArray).WRITE()
	return inst
}

// GetTickArrayAccount gets the "tickArray" account.
func (inst *Swap) GetTickArrayAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

func (inst Swap) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_Swap,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst Swap) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *Swap) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Amount == nil {
			return errors.New("Amount parameter is not set")
		}
		if inst.OtherAmountThreshold == nil {
			return errors.New("OtherAmountThreshold parameter is not set")
		}
		if inst.SqrtPriceLimitX64 == nil {
			return errors.New("SqrtPriceLimitX64 parameter is not set")
		}
		if inst.IsBaseInput == nil {
			return errors.New("IsBaseInput parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Payer is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.AmmConfig is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.PoolState is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.InputTokenAccount is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.OutputTokenAccount is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.InputVault is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.OutputVault is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.ObservationState is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.TickArray is not set")
		}
	}
	return nil
}

func (inst *Swap) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("Swap")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=4]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("              Amount", *inst.Amount))
						paramsBranch.Child(ag_format.Param("OtherAmountThreshold", *inst.OtherAmountThreshold))
						paramsBranch.Child(ag_format.Param("   SqrtPriceLimitX64", *inst.SqrtPriceLimitX64))
						paramsBranch.Child(ag_format.Param("         IsBaseInput", *inst.IsBaseInput))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=10]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("           payer", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("       ammConfig", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("       poolState", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("      inputToken", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("     outputToken", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("      inputVault", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("     outputVault", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("observationState", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("    tokenProgram", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("       tickArray", inst.AccountMetaSlice.Get(9)))
					})
				})
		})
}

func (obj Swap) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Amount` param:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return err
	}
	// Serialize `OtherAmountThreshold` param:
	err = encoder.Encode(obj.OtherAmountThreshold)
	if err != nil {
		return err
	}
	// Serialize `SqrtPriceLimitX64` param:
	err = encoder.Encode(obj.SqrtPriceLimitX64)
	if err != nil {
		return err
	}
	// Serialize `IsBaseInput` param:
	err = encoder.Encode(obj.IsBaseInput)
	if err != nil {
		return err
	}
	return nil
}
func (obj *Swap) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return err
	}
	// Deserialize `OtherAmountThreshold`:
	err = decoder.Decode(&obj.OtherAmountThreshold)
	if err != nil {
		return err
	}
	// Deserialize `SqrtPriceLimitX64`:
	err = decoder.Decode(&obj.SqrtPriceLimitX64)
	if err != nil {
		return err
	}
	// Deserialize `IsBaseInput`:
	err = decoder.Decode(&obj.IsBaseInput)
	if err != nil {
		return err
	}
	return nil
}

// NewSwapInstruction declares a new Swap instruction with the provided parameters and accounts.
func NewSwapInstruction(
	// Parameters:
	amount uint64,
	otherAmountThreshold uint64,
	sqrtPriceLimitX64 ag_binary.Uint128,
	isBaseInput bool,
	// Accounts:
	payer ag_solanago.PublicKey,
	ammConfig ag_solanago.PublicKey,
	poolState ag_solanago.PublicKey,
	inputTokenAccount ag_solanago.PublicKey,
	outputTokenAccount ag_solanago.PublicKey,
	inputVault ag_solanago.PublicKey,
	outputVault ag_solanago.PublicKey,
	observationState ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	tickArray ag_solanago.PublicKey) *Swap {
	return NewSwapInstructionBuilder().
		SetAmount(amount).
		SetOtherAmountThreshold(otherAmountThreshold).
		SetSqrtPriceLimitX64(sqrtPriceLimitX64).
		SetIsBaseInput(isBaseInput).
		SetPayerAccount(payer).
		SetAmmConfigAccount(ammConfig).
		SetPoolStateAccount(poolState).
		SetInputTokenAccountAccount(inputTokenAccount).
		SetOutputTokenAccountAccount(outputTokenAccount).
		SetInputVaultAccount(inputVault).
		SetOutputVaultAccount(outputVault).
		SetObservationStateAccount(observationState).
		SetTokenProgramAccount(tokenProgram).
		SetTickArrayAccount(tickArray)
}
